FROM bde2020/spark-master:3.3.0-hadoop3.3

# Install Python, pip, and necessary dependencies
RUN apk add --no-cache python3 py3-pip build-base python3-dev

# Upgrade pip
RUN pip3 install --upgrade pip

# Install numpy
RUN pip3 install numpy